name: Deploy AWS Lambda Final

on:
  push:
    branches:
      - main
    paths:
      - lambda/**
      
jobs:
  deploy-lambda: #Name of our job
    runs-on: ubuntu-latest # Set-up or specifies our runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies # Installs dependencies for Lambda
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t package/  # Install dependencies in 'package/'
        
      - name: Package and Deploy Lambda Function
        run: |
          rm -f lambda.zip
          mkdir -p package/
          python3 -m pip install -r lambda/requirements.txt -t package/
          cd package || exit 1
          zip -r ../lambda.zip .
          cd ../lambda || exit 1
          zip -g ../lambda.zip lambda_function.py
          zip -g ../lambda.zip requirements.txt
          cd ..
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip --region ca-central-1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1  # Ensure this matches your AWS region

      - name: Debug AWS Credentials
        run: env | grep AWS

      - name: Check AWS Identity
        run: aws sts get-caller-identity

      - name: Deploy to AWS
        run: aws s3 ls  # Example AWS command (replace with your actual deployment step)
        
      - name: Deploy Lambda Function # Deploy the packaged Lambda zip
        run: |
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip