name: Deploy AWS Lambda Final

on:
  push:
    branches:
      - main
    paths:
      - lambda/**
      
jobs:
  deploy-lambda: #Name of our job
    runs-on: ubuntu-latest # Set-up or specifies our runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies # Installs dependencies for Lambda
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t package/  # Install dependencies in 'package/'
        
      - name: Package Lambda Function
        run: |
          rm -f lambda.zip  # Ensure there's no previous ZIP file
          echo "Checking package directory before zipping..."
          ls -lh package/  # Debugging: List installed dependencies
          cd package || exit 1
          zip -r ../lambda.zip .  # Zip all dependencies first
          cd ../lambda || exit 1
          echo "Checking lambda directory before zipping..."
          ls -lh  # Debugging: Ensure lambda_function.py exists
          zip -g ../lambda.zip lambda_function.py  # Add Lambda function code
          zip -g ../lambda.zip requirements.txt  # Include requirements.txt for reference
          cd ..
          ls -lh lambda.zip  # Debugging: Check if zip was created
        
      - name: Configure AWS Creds # Sets up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ca-central-1
        
      - name: Deploy Lambda Function # Deploy the packaged Lambda zip
        run: |
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip