name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Check Lambda Code Exists
        run: ls -la lambda_function.py || { echo "❌ Lambda code missing!"; exit 1; }

      - name: Zip Lambda Function
        run: zip -r lambda_function.zip lambda_function.py

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code --function-name MyLambdaFunction \
            --zip-file fileb://lambda_function.zip || { echo "❌ Deployment failed!"; exit 1; }

      - name: Debugging - Show AWS Lambda Info
        run: aws lambda get-function --function-name MyLambdaFunction